server:
  port: 9393
spring:
  h2:
    console:
      enabled: false
  application:
    name: RESERVATION-SERVICE

eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
  instance:
       hostname: localhost